language: node_js
node_js:
  - '0.10'
  - '0.11'
  - '0.12'
install:
  - 'npm install -g node-gyp grunt grunt-cli bower yo generator-karma generator-angular phonegap'
  - 'npm install'
  - 'bower install'
script:
  - 'npm fullBuild'

